model: # model hyper-parameters
  architecture: TestUNet
  sequences: 1
  width: 24
  deep_supervision: True

optimizer:
  opt: SGD
  lr: 0.001

loss:
  function:  DICE

training:
  debug: False
  seed: 1993
  epochs: 5000
  max_patience: 50

data:
  batch_size: 1
  train_size: 0.8
  classes: [benign, malignant]