model: # model hyper-parameters
  architecture: FSB_BTS_UNet
  sequences: 1
  width: 24
  deep_supervision: True

optimizer:
  opt: Adam
  lr: 0.001

loss:
  function:  DICE

training:
  debug: False
  seed: 1993
  epochs: 5000
  max_patience: 100
  CV: 4
  cuda_benchmark: False
  alpha: 0.8

data:
  semantic_segmentation: False
  input_img: Datasets/Dataset_BUSI_with_GT_postprocessed_128
  batch_size: 1
  train_size: 0.8
  classes: [benign, malignant]
  use_duplicated_to_train: False
  remove_outliers: False
  oversampling: False
  augmentation:
    CLAHE: False
    brightness_brighter: False
    brightness_darker: False
    contrast_high: False
    contrast_low: False
  transforms:
    horizontal_flip: .5
    vertical_flip: .5
    rotation: 1.0