model: # model hyper-parameters
  architecture: BTSUNet
  sequences: 2
  width: 24
  deep_supervision: True

optimizer:
  opt: SGD
  lr: 0.001

loss:
  function:  DICE

training:
  debug: False
  seed: 1993
  epochs: 5000
  max_patience: 100

data:
  batch_size: 1
  train_size: 0.8